baseURL = 'https://ndesilets.com/'
languageCode = 'en-us'
title = 'ndesilets'
theme = 'congo'

[params]
mainSections = ["posts"]

[params.author]
name = 'Nic Desilets'

[params.homepage]
showRecent = true
recentLimit = 6
