baseURL = 'https://ndesilets.com/'
languageCode = 'en-us'
title = 'ndesilets'
theme = 'congo'

outputs.home = ["HTML", "RSS", "JSON"]

[params]
mainSections = ["posts"]

[params.homepage]
layout = "simple"
showRecent = true
recentLimit = 6
